name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PSW }}
        docker build . --file Dockerfile --tag zhuzhengqian123/go-zero-base:1.17 --tag latest
        docker push --all-tags zhuzhengqian123/go-zero-base
